# Generated by Django 6.0 on 2026-01-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
